inherit_from: .rubocop_todo.yml

inherit_gem:
  theforeman-rubocop:
    - lenient.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  Include:
    - 'app/views/api/**/*.rabl'
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'test/**/*.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Style:
  Enabled: false

Layout:
  Enabled: false

Metrics:
  Enabled: false

Naming:
  Enabled: false

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Naming/FileName:
  Exclude:
       - 'Gemfile'
       - 'db/**/*'

Rails/ReversibleMigration:
  Exclude:
       - 'db/migrate/20150111085317_polymorph_asset.rb'

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Performance/InefficientHashSearch:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false
