name: JavaScript Testing

on:
  pull_request:
  push:
    branches:
      - 'master'
      - '*-stable'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint_custom:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version:  ${{ matrix.node-version }}
      - name: Npm install
        run: |
          npm install
      - name: Run plugin linter
        run: |
          npm run lint
      - name: Run custom plugin linter
        run: |
          npm run lint:custom
  test:
    name: JavaScript
    uses: theforeman/actions/.github/workflows/foreman_plugin_js.yml@v0
    with:
      plugin: foreman_openscap
