---
name: Ruby Testing

on:
  push:
    branches:
      - master
      - '*-stable'
  pull_request:

jobs:
  test:
    name: Ruby
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: foreman_openscap
      # https://github.com/theforeman/foreman/pull/9989
      foreman_repository: ofedoren/foreman
      foreman_version: foreman-on-ruby-3-letsgooo
